# deploy_appgw               = 1
cpd_azure_environment      = "test"
cpd_contentful_environment = "test"
environment                = "Test"
instance                   = "d02"
location                   = "westeurope"
project_code               = "s212"
project_name               = "sfsw"
ssl_cert_name              = "support-for-social-workers"
