# deploy_appgw               = 1
cpd_azure_environment      = "pre-prod"
cpd_contentful_environment = "pre-prod"
environment                = "Pre-production"
instance                   = "t01"
location                   = "westeurope"
project_code               = "s212"
project_name               = "sfsw"
ssl_cert_name              = "support-for-social-workers"