name: Whitelist IP Address
description: Adds or updates an allow rule with the user's IP address to the appGw subnet
inputs:
  nsg-name-whitelist:
    description: "Name of the NSG to add the IP address"
    required: true
  infra-resource-group-name:
    description: "Resource Group Name for the NSG"
    required: true
  appgw-subnet:
    description: "Application Gateway subnet name"
    required: true
  rule-name:
    description: "NSG rule name"
    required: true
  ip-address:
    description: "User's IP address to whitelist"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check if rule exists
      shell: bash
      run: |
        echo "Checking for existing rule with IP '${{ inputs.ip-address }}'..."
        ip_exists=$(az network nsg rule list \
          --nsg-name ${{ inputs.nsg-name-whitelist }} \
          --resource-group ${{ inputs.infra-resource-group-name }} \
          --query "[?contains(sourceAddressPrefix, '${{ inputs.ip-address }}')]" \
          -o tsv)
        if [[ -n "$ip_exists" ]]; then
          echo "❌ A rule already exists that allows IP '${{ inputs.ip-address }}'."
          exit 1
        fi
        echo "✅ No existing rule or IP conflict found."

        echo "Checking if rule '${{ inputs.rule-name }}' exists..."
        if az network nsg rule show \
          --nsg-name "${{ inputs.nsg-name-whitelist }}" \
          --resource-group "${{ inputs.infra-resource-group-name }}" \
          --name "${{ inputs.rule-name }}" &>/dev/null; then
          echo "RULE_EXISTS=true" >> "$GITHUB_ENV"
        else
          echo "RULE_EXISTS=false" >> "$GITHUB_ENV"
        fi

    - name: Generate next priority if creating a new rule
      if: env.RULE_EXISTS == 'false'
      shell: bash
      run: |
        echo "Calculating next available priority..."
        priorities=$(az network nsg rule list \
          --nsg-name "${{ inputs.nsg-name-whitelist }}" \
          --resource-group "${{ inputs.infra-resource-group-name }}" \
          --query "[].priority" -o tsv)

        max_priority=500
        for p in $priorities; do
          if [[ $p -gt $max_priority ]]; then
            max_priority=$p
          fi
        done

        NEXT_PRIORITY=$((max_priority + 1))

        if [[ $NEXT_PRIORITY -gt 4096 ]]; then
          echo "Error: Next priority exceeds Azure's maximum (4096)"
          exit 1
        fi

        echo "NEXT_PRIORITY=$NEXT_PRIORITY" >> "$GITHUB_ENV"

    - name: Create new NSG rule
      if: env.RULE_EXISTS == 'false'
      shell: bash
      run: |
        echo "Creating new NSG rule '${{ inputs.rule-name }}'..."

        az network nsg rule create \
          --resource-group "${{ inputs.infra-resource-group-name }}" \
          --nsg-name "${{ inputs.nsg-name-whitelist }}" \
          --name "${{ inputs.rule-name }}" \
          --priority "$NEXT_PRIORITY" \
          --access Allow \
          --direction Inbound \
          --protocol Tcp \
          --source-address-prefixes "${{ inputs.ip-address }}" \
          --source-port-ranges '*' \
          --destination-address-prefixes "${{ inputs.appgw-subnet }}" \
          --destination-port-ranges 80 443

    - name: Update existing NSG rule
      if: env.RULE_EXISTS == 'true'
      shell: bash
      run: |
        echo "Updating existing NSG rule '${{ inputs.rule-name }}'..."

        az network nsg rule update \
          --resource-group "${{ inputs.infra-resource-group-name }}" \
          --nsg-name "${{ inputs.nsg-name-whitelist }}" \
          --name "${{ inputs.rule-name }}" \
          --access Allow \
          --direction Inbound \
          --protocol Tcp \
          --source-address-prefixes "${{ inputs.ip-address }}" \
          --source-port-ranges '*' \
          --destination-address-prefixes "${{ inputs.appgw-subnet }}" \
          --destination-port-ranges 80 443
